recipes/urls.py
from django.urls import path
from recipes import views
from .views import my_recipes_view, add_category_view

app_name = 'recipes'

urlpatterns = [
    path('', views.index, name='index'),
    path('categories/<slug:category_name_slug>/', views.category_view, name='category'),
    path('<int:recipe_id>/', views.recipe_detail_view, name='recipe_detail'),
    path('add-recipe/', views.add_recipe_view, name='add_recipe'),
    path('<int:recipe_id>/edit/', views.edit_recipe_view, name='edit_recipe'),
    path('<int:recipe_id>/delete/', views.delete_recipe_view, name='delete_recipe'),
    path('<int:recipe_id>/comment/', views.comment_view, name='comment'),
    path('<int:recipe_id>/rate/', views.rate_recipe_view, name='rate'),
    path('<int:recipe_id>/save/', views.save_recipe_view, name='save'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('restricted/', views.restricted, name='restricted'),
    path('logout/', views.user_logout, name='logout'),
    path('myrecipes/', my_recipes_view, name='myrecipes'),
    path('category/add/', add_category_view, name='add_category'),
]

wad_recipe_book/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from recipes import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('recipes/', include('recipes.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(blank=True, unique=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Recipe(models.Model):
    DIFFICULTY_CHOICES = [("Easy", "Easy"), ("Medium", "Medium"), ("Hard", "Hard")]

    title = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="recipes")
    image = models.ImageField(upload_to='recipe_images', blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    description = models.TextField()
    difficulty = models.CharField(max_length=20, choices=DIFFICULTY_CHOICES)
    ingredients = models.TextField()
    instructions = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField()

    def average_rating(self):
        ratings = self.ratings.all()
        if ratings.exists():
            return round(sum(r.rating for r in ratings) / ratings.count(), 1)
        return 0
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Recipe, self).save(*args, **kwargs)

    def __str__(self):
        return self.title


class SavedRecipe(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='saved_recipes')
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='saved_by')
    saved_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'recipe')  # Prevent duplicate saves

    def __str__(self):
        return f"{self.user.username} saved {self.recipe.title}"


class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ratings')
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='ratings')
    rating = models.IntegerField(choices=[(i, i) for i in range(1, 6)])  # 1 to 5 stars
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'recipe')  # Ensures a user can rate a recipe only once

    def __str__(self):
        return f"{self.user.username} rated {self.recipe.title} {self.value}/5"

    

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='comments')
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} commented on {self.recipe.title}"


class UserProfile(models.Model):
    
    user = models.OneToOneField(User, on_delete = models.CASCADE)
     
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)
    
    def __str__(self):
        return self.user.username

recipes/forms.py
from django import forms 
from django.contrib.auth.models import User
from recipes.models import Rating, Recipe, UserProfile, Category

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    
    class Meta: 
        model = User
        fields = ('username', 'email', 'password',)
        
class UserProfileForm(forms.ModelForm): 
    class Meta:
        model = UserProfile
        fields = ('website', 'picture',)


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['title', 'image', 'difficulty', 'category', 'description', 'ingredients', 'instructions']
        
        widgets = {
            'description': forms.Textarea(attrs={'rows': 3}),
            'ingredients': forms.Textarea(attrs={'rows': 3}),
            'instructions': forms.Textarea(attrs={'rows': 5}),
            'difficulty': forms.Select(choices=Recipe.DIFFICULTY_CHOICES),
        }

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Please Enter the new Category name:'}),
        }

class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ["rating"]  # Only allow selecting a rating (1-5)

# class RecipeForm(forms.ModelForm):
#     title = forms.CharField(max_length=128, help_text="Please enter the title of the page.")
#     picture = forms.ImageField()
#     description = forms.CharField(max_length=255, help_text="Please enter a description")
#     prep_time = forms.IntegerField(max_value=100, help_text="Preparation time in minutes")
#     difficulty = forms.ChoiceField()
#     ingredients = forms.CharField()
#     instructions = forms.Textarea()

#     class Meta:
#         model = Recipe
#         exclude = ('author', 'category','created_at', 'rating', 'slug')

class CommentForm(forms.ModelForm):
    pass

recipes/views.py
from recipes.forms import CommentForm, RatingForm, RecipeForm, UserForm, UserProfileForm
from django.shortcuts import redirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from recipes.models import Category, Rating, Recipe
from datetime import datetime
from django.http import JsonResponse
from recipes.models import Recipe, SavedRecipe
from .forms import CategoryForm

# Create your views here.

def index(request):
    context = get_categories()
    return render(request, 'recipes/index.html', context=context)

def get_categories():
    context_dict = {}
    try:
        categories = Category.objects.all() 
        context_dict['categories'] = categories
    except Category.DoesNotExist:
        context_dict['categories'] = None
    return context_dict



@login_required
def add_category_view(request):
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('recipes:myrecipes')  
    else:
        form = CategoryForm()
    return render(request, 'recipes/add_category.html', {'form': form})

def category_view(request, category_name_slug):
    context_dict = {}

    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Recipe.objects.filter(category=category)
        context_dict['recipes'] = pages
        context_dict['category'] = category
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['recipes'] = None

    return render(request, 'recipes/category.html', context=context_dict)


def recipe_detail_view(request, recipe_id):
    recipe = Recipe.objects.get(id=recipe_id)
    return render(request, 'recipes/recipe.html', {'recipe': recipe})

  
def add_recipe_view(request):
    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES)
        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.author = request.user
            recipe.save()
            return redirect('/')
    else:
        form = RecipeForm()
    return render(request, 'recipes/addrecipe.html', {'form': form})

  
def edit_recipe_view(request, recipe_id):
    recipe = Recipe.objects.get(id=recipe_id)
    if recipe.author != request.user:
        return HttpResponseForbidden("You are not allowed to edit this recipe.")
    
    if request.method == 'POST':
        form = RecipeForm(request.POST, instance=recipe)
        if form.is_valid():
            form.save()
            return render(request, "recipes/recipe.html", {"recipe": recipe})
    else:
        form = RecipeForm(instance=recipe)
    return render(request, 'recipes/editrecipe.html', {'form': form, 'recipe': recipe})

  
def delete_recipe_view(request, recipe_id):
    recipe = Recipe.objects.get(id=recipe_id)
    if request.method == 'POST':
        recipe.delete()
        return redirect('/')
    return render(request, 'recipes/deleterecipe.html', {'recipe': recipe})

  
def comment_view(request, recipe_id):
    recipe = Recipe.objects.get(id=recipe_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.recipe = recipe
            comment.save()
    return redirect(request.META.get('HTTP_REFERER', '/'))
  
  
@login_required
def rate_recipe_view(request, recipe_id):
    recipe = Recipe.objects.get(id=recipe_id)
    rating_instance = Rating.objects.filter(user=request.user, recipe=recipe).first()

    if request.method == "POST":
        form = RatingForm(request.POST, instance=rating_instance)  # Use existing rating if it exists
        if form.is_valid():
            rating = form.save(commit=False)
            rating.user = request.user
            rating.recipe = recipe
            rating.save()
            return render(request, 'recipes/recipe.html', {'recipe': recipe})

    else:
        form = RatingForm(instance=rating_instance)

    return render(request, "recipes/raterecipe.html", {"form": form, "recipe": recipe})

@login_required
def my_recipes_view(request):
    saved_recipes = SavedRecipe.objects.filter(user=request.user).select_related('recipe')
    recipes = [saved.recipe for saved in saved_recipes]
    context = {'recipes': recipes}
    return render(request, 'recipes/myrecipes.html', context)

@login_required
def save_recipe_view(request, recipe_id):
    if request.method == "POST":
        try:
            recipe = Recipe.objects.get(id=recipe_id)
            saved_recipe = SavedRecipe.objects.filter(user=request.user, recipe=recipe).first()
            if saved_recipe:
                saved_recipe.delete()
                return JsonResponse({"unsaved": True})
            else:
                SavedRecipe.objects.create(user=request.user, recipe=recipe)
                return JsonResponse({"saved": True})
        except Recipe.DoesNotExist:
            return JsonResponse({"error": "Recipe not found."}, status=404)
        except Exception as e:
            return JsonResponse({"error": str(e)}, status=500)
    else:
        return JsonResponse({"error": "Invalid request method."}, status=400)

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'recipes/register.html', context={'user_form': user_form, 'profile_form': profile_form, 'registered': registered})

  
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
  
        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('recipes:index'))
            else:
                return HttpResponse("Your account is disabled.")
        else:
            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'recipes/login.html')
    
    
def some_view(request):
    if not request.user.is_authenticated():
        return HttpResponse("You are logged in.") 
    else:
        return HttpResponse("You are not logged in.")

      
@login_required
def restricted(request):
    return HttpResponse("Since you're logged in, you can see this text!")
  

@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('recipes:index'))

templates/recipes/add_category.html
{% extends 'recipes/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add new category
{% endblock %}

{% block body_block %}
    <h1>Add new category</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add category</button>
    </form>
{% endblock %}

templates/recipes/addrecipe.html
{% extends 'recipes/base.html' %}
{% load staticfiles %}

{% block title_block %}
{% endblock %}

{% block body_block %}
    <div class="form-container">
        <form id="recipe_form" method="post" action="{% url 'recipes:add_recipe' %}" id="recipe_form">
            <h1 class="form-title">Add recipe</h1>
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form>
    </div>
{% endblock %}

templates/recipes/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
    <head lang="en">
        <meta charset="UTF-8" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
        <style>
            @import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
        </style>
        <title>
            {% block title_block %}
            {% endblock %}
        </title>
    </head>

    <header>
        <nav class="navbar">
            <ul>
                <li><img src="{% static 'images/recipeicon.png' %}" alt="My recipes Icon" width="75" height="75"/></li>
                <li class="navbar-title">Snack Overflow</li>
                <li><a href="{% url 'recipes:index' %}">Home</a></li>
                {% if user.is_authenticated %}
                <!-- Show these links when the user is logged in -->
                <li><a href="{% url 'recipes:add_recipe' %}">Add Recipe</a></li>
                <li><a href="{% url 'recipes:logout' %}">Logout</a></li>
                {% else %}
                <!-- Show these links when the user is NOT logged in -->
                <li><a href="{% url 'recipes:register' %}">Sign Up</a></li>
                <li><a href="{% url 'recipes:login' %}">Login</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    {% block extra_scripts %}{% endblock %}
    <body>
        <div>
            {% block body_block %}
            {% endblock %}
        </div>
    </body>

    <footer>
        {% block footer_block %}
            <p class="footer-content">Web App Development Group Project Team 7 </p>
        {% endblock %}
    </footer>
</html>

templates/recipes/category.html
{% extends 'recipes/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Categories
{% endblock %}

{% block body_block %}
    {% if category %}
        <h1 class="category-heading">{{ category.name }}</h1>
        {% if recipes %}
            <div class="recipe-list-container">
                <ul class="recipe-list">
                    {% for recipe in recipes %}
                    <li class="recipe-item"><a class="recipe-link" href="{% url 'recipes:recipe_detail' recipe.id %}">{{ recipe.title }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <div class="categories-container">
                <div>
                    {% else %}
                <strong class="no-recipes-message">No pages currently in category.</strong>
            {% endif %}

            {% if user.is_authenticated %}
                <a class="add-recipe-link" href="{% url 'recipes:add_recipe' %}">Add Page</a> <br />
            {% endif %}
        {% else %}
                <p class="category-error-message">The specified category does not exist.</p>
                </div>
            </div>
    {% endif %}
{% endblock %}

templates/recipes/comment.html
<!DOCTYPE html>

{% load staticfiles %}
<html>
<head>
    <title>Snack Overflow</title>
</head>

<body>
<h5>Home</h5>
<!-- TODO should change depending on name of recipe -->
<h1>Recipe Name</h1>
<!-- TODO load image of recipe -->
<img src="{% static '' %}"
     alt="recipe Icon" width="75" height="75"/><br><br>

<div>
    <form id="comment_form" method="post" action="{% url 'recipes:comment' %}">
        <label for="comment">Leave a comment:</label>
        <input type="text" id="comment" name="comment"><br><br>
        <input type="submit" value="Confirm">
    </form>
</div>


</body>
</html>

templates/recipes/editrecipe.html
{% extends 'recipes/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Snack Overflow
{% endblock %}

{% block body_block %}
<h2>Edit Recipe: {{ recipe.title }}</h2>

<div>
    <form id="edit_form" method="post" action="{% url 'recipes:edit_recipe' recipe.id %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Confirm">
    </form>
</div>
{% endblock %}

templates/recipes/index.html
{% extends 'recipes/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Home
{% endblock %}

{% block body_block %}
<div>
    <ul id="category-list">
        {% if categories %}
            {% for category in categories %}
                <li class="category-item" {% if forloop.counter > 3 %} style="display: none;" {% endif %}>
                    <a href="{% url 'recipes:category' category.slug %}">{{ category.name }}</a>
                </li>
            {% endfor %}
        {% endif %}
    </ul>
    {% if categories|length > 3 %}
        <button id="toggle-categories" type="button">Show more categories.</button>
    {% endif %}
</div>

<div>
    <h5>Log in/Sign up</h5>
    <img src="{% static 'images/profileicon.png' %}" alt="Profile Icon" width="75" height="75"/>
</div>

<div>
    <a href="{% url 'recipes:add_recipe' %}">Add recipes</a>
    <br><br>
    <img src="{% static 'images/addrecipeicon.png' %}" alt="Add Recipe Icon" width="75" height="75"/>
</div>

<div>
    <a href="{% url 'recipes:myrecipes' %}">My Recipes</a>
    <br><br>
    <img src="{% static 'images/recipeicon.png' %}" alt="My recipes Icon" width="75" height="75"/>
</div>

{% if user.is_authenticated %}
    <a href="{% url 'recipes:add_category' %}">Add category</a>
{% endif %}
{% endblock %}

{% block extra_scripts %}
    <script src="{% static 'js/script.js' %}"></script>
    <script>
    document.addEventListener("DOMContentLoaded", function() {
        const toggleBtn = document.getElementById("toggle-categories");
        if (toggleBtn) {
            toggleBtn.addEventListener("click", function() {
                if (toggleBtn.innerText.trim() === "Show more categories.") {
                    const categoryItems = document.querySelectorAll("#category-list .category-item");
                    categoryItems.forEach(item => {
                        item.style.display = "list-item";
                    });
                    toggleBtn.innerText = "Show less categories.";
                }
                else if (toggleBtn.innerText.trim() === "Show less categories.") {
                    window.location.reload();
                }
            });
        }
    });
    </script>
{% endblock %}

templates/recipes/login.html
{% extends 'recipes/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
    <h1>Log in</h1>
    <img src="{% static 'images/profileicon.png' %}"
        alt="Profile Icon" width="75" height="75"/>
    <div>
        <form id="login_form" method="post" action="{% url 'recipes:login' %}">
            {% csrf_token %}
            Username: <input type="text" name="username" value="" size="30" />
            <br />
            Password: <input type="password" name="password" value="" size="30" />
            <br />
            <input type="submit" value="submit" />
        </form>
    </div>
{% endblock %}

templates/recipes/myrecipes.html
{% extends 'recipes/base.html' %}
{% load staticfiles %}

{% block title_block %}
    My Recipes
{% endblock %}

{% block body_block %}
    <h1>My Saved Recipes</h1>
    {% if recipes %}
        <ul>
            {% for recipe in recipes %}
                <li>
                    <a href="{% url 'recipes:recipe_detail' recipe.id %}">
                        {{ recipe.title }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>You haven't saved any recipes yet.</p>
    {% endif %}
{% endblock %}

templates/recipes/raterecipe.html
{% extends 'recipes/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Snack Overflow
{% endblock %}

{% block body_block %}
<h2>Rate Recipe: {{ recipe.title }}</h2>

<div>
    <form id="rating_form" method="post" action="{% url 'recipes:rate' recipe.id %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Confirm">
    </form>
</div>
{% endblock %}

templates/recipes/recipe.html
{% extends 'recipes/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Recipe
{% endblock %}


{% block body_block %}
    {% if recipe %}
        <h1 id="recipe-title">{{ recipe.title }}</h1>
        <h3 id="author">By {{ recipe.author }}</h3>
        <h3 id="difficulty">Difficulty: {{ recipe.difficulty }}</h3>
        <img class="recipe-image" src="{{ recipe.image }}" alt="{{ recipe.title }}">
        <div class="description">
            <h3>Description</h3>
            <p> {{ recipe.description }} </p>
        </div>
        <h3>Instructions</h3>
        <p> {{ recipe.instructions }} </p>
        <h3> Rating: {{ recipe.average_rating }} / 5.0</h3>

        {% if user.is_authenticated %}
            <span class="like-count">{{ recipe.total_likes|default:"0" }}</span>
            
            <button class="save-recipe" data-recipe-id="{{ recipe.id }}">Save to My Recipes</button>
            
            <form method="post" action="{% url 'recipes:rate' recipe.id %}">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Rate</button>
            </form>
            
            <a href="{% url 'recipes:edit_recipe' recipe.id %}">Edit Recipe</a>
        {% endif %}


    {% else %}
        The specified recipe does not exist.
    {% endif %}
{% endblock %}
{% block extra_scripts %}
    <script src="{% static 'js/script.js' %}"></script>
{% endblock %}

templates/recipes/register.html
{% extends 'recipes/base.html' %}
{% load staticfiles %}


{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
    <h1>Sign Up</h1>
    <img src="{% static 'images/profileicon.png' %}"
        alt="Profile Icon" width="75" height="75"/>
    <div>
        <form id="register_form" method="post" action="{% url 'recipes:register' %}">
            {% csrf_token %}
            Username: <input type="text" name="username" value="" size="30" />
            <br />
            Password: <input type="password" name="password" value="" size="30" />
            <br />
            <input type="submit" value="submit" />
        </form>
    </div>
{% endblock %}

templates/recipes/saverecipe.html
<!DOCTYPE html>

{% load staticfiles %}
<html>
<head>
    <title>Snack Overflow</title>
</head>

<body>
<h5>Home</h5>
<!-- TODO should change depending on name of recipe -->
<h1>Recipe Name</h1>
<!-- TODO load image of recipe -->
<img src="{% static '' %}"
     alt="add recipe Icon" width="75" height="75"/><br><br>

<h3>Save Recipe to profile?</h3>
<div>
    <form id="save_form" method="post" action="{% url 'recipes:save' %}">
        <input type="checkbox" id="yes" name="yesbutton" value="Yes">
        <label for="yes"> Yes</label><br>
        <input type="checkbox" id="no" name="nobutton" value="No">
        <label for="no"> No</label><br>
        <input type="submit" value="Submit">
    </form>
</div>


</body>
</html>